# Generated by Django 3.2.7 on 2021-10-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_recipe_iddisplayed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='idDisplayed',
        ),
        migrations.AddField(
            model_name='recipe',
            name='isDisplayed',
            field=models.BooleanField(default=False),
        ),
    ]
