# Generated by Django 3.2.7 on 2021-09-28 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_material_process_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cost',
            field=models.PositiveIntegerField(),
        ),
    ]
