# Generated by Django 3.2.7 on 2021-10-16 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_recipe_iddisplayed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='idDisplayed',
            new_name='isDisplayed',
        ),
    ]
