# Generated by Django 3.2.7 on 2021-09-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_material_process_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='recipe_id',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='process',
            old_name='recipe_id',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cost',
            field=models.PositiveIntegerField(),
        ),
    ]
