# Generated by Django 3.2.7 on 2021-10-18 10:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_iddisplayed_recipe_isdisplayed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='isDisplayed',
        ),
        migrations.AddField(
            model_name='recipe',
            name='isDisplayed',
            field=models.ManyToManyField(blank=True, related_name='isDisplayed', to=settings.AUTH_USER_MODEL),
        ),
    ]
