# Generated by Django 3.2.7 on 2021-09-28 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_recipe_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='recipe_id',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='process',
            old_name='recipe_id',
            new_name='recipe',
        ),
    ]
