# Generated by Django 3.2.7 on 2021-10-02 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_mypage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material', to='api.recipe'),
        ),
        migrations.AlterField(
            model_name='process',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process', to='api.recipe'),
        ),
    ]
