# Generated by Django 3.2.7 on 2021-10-03 07:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20211003_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
